# Generated by Django 3.1.3 on 2020-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201203_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='краткое описание'),
        ),
    ]
